### ISSUE TITLE
No longer maintained

### ISSUE THREAD

**Issue by GaryIrick** [Will-McBurney/NGSSimulator#1]
@Will-McBurney , since you are no longer in the league or maintaining this, do you have any objections to me borrowing parts of it   and building something similar?  My plan would be to hand it off to the league with instructions on care and feeding so the tech team can handle it going forward.

I could build something from scratch without digging into the source, but it would give me a much better place to start if I can lift some pieces that I know are already solid.

Thanks!

**Comment by Will-McBurney** [comment]
You can do whatever you want with it. It's a public github.

The current .ps file and .jar file should work for anything unless/until the following:

1) Each new season, you need to make a new teams.csv file in the data folder. Just match the format that's there
2) Once the schedule is posted, you should be able to use the schedule_getter.py in data/schedules, but you may need to update the source code, specifically there's a dictionary that lists all the divisions that you'll need to update. The rest of it should still work
3) You'll want to update the divisions in the .ps file if the divisions change


I'm very willing to provide some support on this, I'm just done with participating in the league because of repeated toxic behavior directed at me very publicly without response or reprimand.
